version: '3.8'

services:
  token_server:
    image: dannymateoh1/token_server:v1
    container_name: token_server
    ports:
      - "5000:5000"

  token_client:
    image: dannymateoh1/token_client:v1
    container_name: token_client
    depends_on:
      - token_server
    stdin_open: true
    tty: true
